---
- name: Create kube-proxy config.yml
  template:
    src: kube-proxy-config.yaml.j2
    dest: "{{ kube_dir }}/kube-proxy-config.yml"
  notify:
    - Restart kube-proxy service

- name: Create kube-proxy systemd unit file
  template:
    src: kube-proxy.service.j2
    dest: /etc/systemd/system/kube-proxy.service
  notify:
    - Restart kube-proxy service

- name: flush handlers
  meta: flush_handlers

