---

- name: Stop firewalld NetworkManager
  systemd: 
    name: "{{ item }}"
    enabled: no
    state: stopped
  failed_when: false
  with_items:
    - firewalld
    - NetworkManager

- name: Set timezone for {{ TimeZone }}
  timezone:
    name: "{{ TimeZone }}"

- name: Temporary disable for selinux
  shell: |
    setenforce 0
  failed_when: false

- name: Permanent disable for  selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"

- name: Create hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
