---

- name: Create kube-controller-manager systemd unit file
  template:
    src: kube-controller-manager.service.j2
    dest: /etc/systemd/system/kube-controller-manager.service
  notify:
    - Restart kube-controller-manager service

- name: <kube-controller-manager> 设置默认上下文
  shell: |
    cd {{ kube_ssl }} && \
    {{ kubectl }} config use-context system:kube-controller-manager --kubeconfig=kube-controller-manager.kubeconfig
  when: inventory_hostname in groups['master'][0]
