---

- name: debug kube_apiserver address
  debug:
    msg: "{{ kube_apiserver }}"

- name: <kubectl>设置集群参数
  shell: |
    cd {{ cfssl_dir }} && \
    {{ kubectl }} config set-cluster kubernetes --certificate-authority=ca.pem \
    --embed-certs=true --server={{ kube_apiserver }} --kubeconfig=kube.config

- name: <kubectl>设置客户端认证参数
  shell: |
    cd {{ cfssl_dir }} && \
    {{ kubectl }} config set-credentials admin --client-certificate=admin.pem \
    --client-key=admin-key.pem --embed-certs=true --kubeconfig=kube.config

- name: <kubectl>设置上下文参数
  shell: |
    cd {{ cfssl_dir }} && \
    {{ kubectl }} config set-context kubernetes --cluster=kubernetes --user=admin --kubeconfig=kube.config

- name: <kubectl>设置默认上下文
  shell: |
    cd {{ cfssl_dir }} && \
    {{ kubectl }} config use-context kubernetes --kubeconfig=kube.config


- name: <kube-controller-manager> 设置集群参数
  shell: |
    cd {{ cfssl_dir }} && \
    {{ kubectl }} config set-cluster kubernetes --certificate-authority=ca.pem \
    --embed-certs=true --server={{ kube_apiserver }} --kubeconfig=kube-controller-manager.kubeconfig

- name: <kube-controller-manager>设置客户端认证参数
  shell: |
    cd {{ cfssl_dir }} && \
    {{ kubectl }} config set-credentials system:kube-controller-manager --client-certificate=kube-controller-manager.pem \
     --client-key=kube-controller-manager-key.pem --embed-certs=true --kubeconfig=kube-controller-manager.kubeconfig

- name: <kube-controller-manager> 设置上下文参数
  shell: |
    cd {{ cfssl_dir }} && \
    {{ kubectl }} config set-context system:kube-controller-manager --cluster=kubernetes \
    --user=system:kube-controller-manager --kubeconfig=kube-controller-manager.kubeconfig

- name: <kube-controller-manager> 设置默认上下文
  shell: |
    cd {{ cfssl_dir }} && \
    {{ kubectl }} config use-context system:kube-controller-manager --kubeconfig=kube-controller-manager.kubeconfig

- name: <kube-scheduler> 设置集群参数
  shell: |
    cd {{ cfssl_dir }} && \
    {{ kubectl }} config set-cluster kubernetes --certificate-authority=ca.pem --embed-certs=true \
    --server={{ kube_apiserver }} --kubeconfig=kube-scheduler.kubeconfig

- name: <kube-scheduler> 设置客户端认证参数
  shell: |
    cd {{ cfssl_dir }} && \
    {{ kubectl }} config set-credentials system:kube-scheduler --client-certificate=kube-scheduler.pem \
    --client-key=kube-scheduler-key.pem --embed-certs=true --kubeconfig=kube-scheduler.kubeconfig
 
- name: <kube-scheduler> 设置上下文参数
  shell: |
    cd {{ cfssl_dir }} && \
    {{ kubectl }} config set-context system:kube-scheduler --cluster=kubernetes \
    --user=system:kube-scheduler --kubeconfig=kube-scheduler.kubeconfig

- name: <kube-scheduler> 设置默认上下文
  shell: |
    cd {{ cfssl_dir }} && \
    {{ kubectl }} config use-context system:kube-scheduler --kubeconfig=kube-scheduler.kubeconfig

- name: <kubelet-bootstrap.kubeconfig> 设置集群参数
  shell: |
    cd {{ cfssl_dir }} && \
    {{ kubectl }} config set-cluster kubernetes --certificate-authority=ca.pem \
    --embed-certs=true --server={{ kube_apiserver }} --kubeconfig=kubelet-bootstrap.kubeconfig

- name: <kubelet-bootstrap.kubeconfig> 设置客户端认证参数
  shell: |
    cd {{ cfssl_dir }} && \
    {{ kubectl }} config set-credentials kubelet-bootstrap --token={{ token_str }} --kubeconfig=kubelet-bootstrap.kubeconfig

- name: <kubelet-bootstrap.kubeconfig> 设置上下文参数
  shell: |
    cd {{ cfssl_dir }} && \
    {{ kubectl }} config set-context default --cluster=kubernetes --user=kubelet-bootstrap --kubeconfig=kubelet-bootstrap.kubeconfig

- name: <kubelet-bootstrap.kubeconfig> 设置默认上下文
  shell: |
    cd {{ cfssl_dir }} && \
    {{ kubectl }} config use-context default --kubeconfig=kubelet-bootstrap.kubeconfig

- name: <kube-proxy> 设置集群参数
  shell: |
    cd {{ cfssl_dir }} && \
    {{ kubectl }} config set-cluster kubernetes --certificate-authority=ca.pem --embed-certs=true \
    --server={{ kube_apiserver }} --kubeconfig=kube-proxy.kubeconfig

- name: <kube-proxy> 设置客户端认证参数
  shell: |
    cd {{ cfssl_dir }} && \
    {{ kubectl }} config set-credentials kube-proxy --client-certificate=kube-proxy.pem \
    --client-key=kube-proxy-key.pem --embed-certs=true --kubeconfig=kube-proxy.kubeconfig 

- name: <kube-proxy> 设置上下文参数
  shell: |
    cd {{ cfssl_dir }} && \
    {{ kubectl }} config set-context default --cluster=kubernetes --user=kube-proxy --kubeconfig=kube-proxy.kubeconfig

- name: <kube-proxy> 设置默认上下文
  shell: |
    cd {{ cfssl_dir }} && \
    {{ kubectl }} config use-context default --kubeconfig=kube-proxy.kubeconfig
