---

##########
# Ceph MDS
##########
cephfs_data_pool_name: "cephfs_data"
cephfs_data_pool_type: "{{ ceph_pool_type }}"
cephfs_data_pool_cache_mode: "{{ ceph_cache_mode }}"
cephfs_data_pool_pg_num: "{{ ceph_pool_pg_num }}"
cephfs_data_pool_pgp_num: "{{ ceph_pool_pgp_num }}"
cephfs_metadata_pool_name: "cephfs_metadata"
cephfs_metadata_pool_type: "{{ ceph_pool_type }}"
cephfs_metadata_pool_cache_mode: "{{ ceph_cache_mode }}"
cephfs_metadata_pool_pg_num: "{{ ceph_pool_pg_num }}"
cephfs_metadata_pool_pgp_num: "{{ ceph_pool_pgp_num }}"

ceph_mds_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ ceph_install_type }}-ceph-mds"
ceph_mds_tag: "{{ ceph_tag }}"
ceph_mds_image_full: "{{ ceph_mds_image }}:{{ ceph_mds_tag }}"

ceph_client_mds_keyring_caps:
  mds: 'allow *'
  osd: 'allow *'
  mon: 'allow rwx'

ceph_nfs_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ ceph_install_type }}-cephfs-fuse"
ceph_nfs_tag: "{{ ceph_tag }}"
ceph_nfs_image_full: "{{ ceph_nfs_image }}:{{ ceph_nfs_tag }}"