---

- name: Get system data
  script: check_linux.sh
  register: inspection_result


- name: Generate json data
  debug:
    msg: "{{ hostvars | os_inspection_filter }}"
  connection: local
  run_once: true
