---

- name: Restart kubelet service
  systemd:
    name: kubelet
    state: restarted
    enabled: true
    daemon_reload: true

- name: Restart kube-proxy service
  systemd:
    name: kube-proxy
    state: restarted
    enabled: true
    daemon_reload: true
