---
- hosts: all
  gather_facts: false
  tasks:
  - name: Setup host vars
    setup:
      filter: "{{ item }}"
    register: hostinfo
    with_items:
      - "ansible_hostname"
      - "ansible_devices"
      - "ansible_{{ storage_interface }}"
      - "ansible_{{ cluster_interface }}"
    tags: always

  - name: Set_fact host vars
    set_fact: host_vars={{ hostinfo.results }}
    tags: always

  - name: Create ceph-mon 
    import_role: 
      name: ceph-mon
    tags:
      - always

  - name: Create ceph-mgr
    import_role:
      name: ceph-mgr
    tags:
      - ceph-mgr

  - name: Create ceph-osd
    import_role:
      name: ceph-osd
    tags:
      - ceph-osd

  - name: Create ceph-rgw
    import_role:
      name: ceph-rgw
    tags:
      - ceph-rgw

  - name: Create ceph-mds
    import_role:
      name: ceph-mds
    tags:
      - ceph-mds
