---

- include_tasks: start_mgrs.yml
  when: inventory_hostname in groups['ceph-mgr']

- name: Enable ceph dashboard
  become: true
  command: docker exec ceph_mon ceph mgr module enable dashboard --force
  changed_when: false
  run_once: true
  when:
    - enable_ceph_dashboard | bool
    - inventory_hostname in groups['ceph-mon']
