---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx

spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: 172.20.163.244:5000/nginx:v1
        ports:
        - containerPort: 80
