---

####################
# Docker options
####################

# Docker regisry. 172.17.2.179:5000
docker_registry: "172.20.163.244:5000"



#####################
# Ceph options
####################
# Ceph cluser id
ceph_cluster_fsid: "4a9e463a-4853-4237-a5c5-9ae9d25bacda"
# Ceph build container tag
ceph_tag: "nautilus"
# Bluestore or filestore
ceph_osd_store_type: "bluestore"
# erasure or replicated
ceph_pool_type: "replicated"

# ceph osd host number
ceph_osd_host_num: "{{ groups['osd'] | length }}"
# Fault domain: host or osd
ceph_domain: "{{ 'osd' if ceph_osd_host_num|int < 3  else 'host' }}"
# Rules define fault domain types
ceph_rule: "default {{ ceph_domain }} {{ 'indep' if ceph_pool_type == 'erasure' else 'firstn' }}"

# Ceph pool pg number
ceph_pool_pg_num: 32
# Ceph pool pgp number
ceph_pool_pgp_num: 32
#enable_ceph_rgw: true or false
enable_ceph_rgw: true
#Ceph rgw port
radosgw_port: 7480
# enable_ceph_mds: true or false
enable_ceph_mds: false
# enable_ceph_nfs: true or false
enable_ceph_nfs: false
# enable_ceph_dashboard: true or false
enable_ceph_dashboard: true
