---

ceph_client_mgr_keyring_caps:
  mon: 'allow profile mgr'
  osd: 'allow *'
  mds: 'allow *'

ceph_mgr_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ ceph_install_type }}-ceph-mgr"
ceph_mgr_tag: "{{ ceph_tag }}"
ceph_mgr_image_full: "{{ ceph_mgr_image }}:{{ ceph_mgr_tag }}"