---
- hosts: all
  gather_facts: false

  tasks:
    - name: Apply role check with inspection 
      import_role:
        name: inspection
      tags: inspection


    - name: Apply role check with platform_inspection
      import_role:
        name: platform_inspection
      tags: platform


- hosts: localhost
  gather_facts: false
  tasks:
    - name: process platform json data
      platform_process:
        platform_json: "{{ platform_inspection_path }}"
        os_json: "{{ os_inspection_path }}"
        report_json_path: "{{ report_json_path }}"
      tags: process
