---
- include_tasks: config.yml

- include_tasks: bootstrap_mons.yml
  when: inventory_hostname in groups['ceph-mon']

- include_tasks: distribute_keyrings.yml
  when: kolla_ceph_action != "upgrade"

- include_tasks: start_mons.yml
  when: inventory_hostname in groups['ceph-mon']

- name: configuring client.admin caps
  become: true
  kolla_ceph_keyring:
    name: client.admin
    caps: "{{ ceph_client_admin_keyring_caps }}"
  run_once: True
  delegate_to: "{{ groups['ceph-mon'][0] }}"
  register: result
  until: result is success
  retries: 3
  delay: 15
