---
- name: Checking free port for docker registry
  wait_for:
    host: "{{ docker_registry.split(':')[0] }}"
    port: "{{ docker_registry.split(':')[1] }}"
    connect_timeout: 1
    timeout: 1
    state: started
  when:
    - inventory_hostname in groups['ceph-mon'][0]
