---

####################
# Ceph
####################

ceph_mon_tag: "{{ ceph_tag }}"
ceph_mon_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ ceph_install_type }}-ceph-mon"
ceph_mon_image_full: "{{ ceph_mon_image }}:{{ ceph_mon_tag }}"

distro_python_version: "2.7"

ceph_client_admin_keyring_caps:
  mds: "allow *"
  mon: "allow *"
  osd: "allow *"
  mgr: "allow *"

