---

- hosts: localhost
  gather_facts: false
  tasks:

  - name: generate xlsx
    generate_xlsx:
      src_data:  "{{ report_json_path }}" 
      save_path: "{{ report_path }}"
      xlsx_template: "{{ xlsx_template_path }}"
    tags: generate
